### ISSUE TITLE
three calls to MNIST

### ISSUE THREAD

**Issue by antonkratz** [NVDLI/LDL#1]
> However, the code snippet below contains three calls to MNIST. The reason for that is that we want to first access the training dataset to compute the mean and standard deviation.

`trainset = MNIST(root='./pt_data', train=True, download=True, transform=transform)`

But why the second call defining trainset? You already loaded trainset once to define mean and stdev. Why call it a second time?

**Comment by magnus-ekman** [comment]
Yes, I agree that it looks ugly but couldn't think of a better way. I modify the transform based on the mean and stddev so when I load it the second time around it will be transformed differently. Is there a good way to apply a new transform to an already loaded dataset that lets me avoid loading it a second time?
