### ISSUE TITLE
Skip Unicode BOM when opening txt files.

### ISSUE THREAD

**Issue by iabdalkader** [NVDLI/LDL#3]
Hi, the examples that use text files with Byte Order Marker (BOM), like `frankenstein.txt`, should use `encoding='utf-8-sig'` instead of `utf-8` to skip the BOM, otherwise you get this:

```Python
In [4]: with open('frankenstein.txt', 'r', encoding='utf-8') as f:
   ...:     text = text_to_word_sequence(f.read())
   ...: print(text[0:5])

['\ufeffthe', 'project', 'gutenberg', 'ebook', 'of']
```

I realize it doesn't matter much, but it was confusing to see that word in there. One more note, `np.int` is [deprecated](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).

Great book, thanks!

**Comment by magnus-ekman** [comment]
I'm glad you like the book and thanks for pointing out these issues. I'll submit a fix soon.

**Comment by magnus-ekman** [comment]
This issue is now addressed. Closing.
