### ISSUE TITLE
Pickle

### ISSUE THREAD

**Issue by vrobot-2** [NVDLI/LDL#4]
I can't find or use pickle.Gzip and don't know this, quite a beginner

**Comment by magnus-ekman** [comment]
Can you provide some more information? Is this for c16e1_create_vectors.py? Or are you trying to run c16e2_image_captioning.py without having first run c16e1_create_vectors.py? The way this is intended to work is that c16e1_create_vectors.py creates a large number of files ending in .pickle.gzip, and these files are later opened by c16e2_image_captioning.py.
