### ISSUE TITLE
Fine not found in c12e1_autocomplete_embedding.ipynb

### ISSUE THREAD

**Issue by SeryioGonzalez** [NVDLI/LDL#9]
The first code cell has a variable pointing to a file:

_INPUT_FILE_NAME = '../data/frankenstein.txt'_

Then, in the second cell, this line fails

_file = open(INPUT_FILE_NAME, 'r', encoding='utf-8-sig')_

**Comment by magnus-ekman** [comment]
Did you download the datasets as described in the README file? For this specific example, read the section "FRANKENSTEIN FROM PROJECT GUTENBERG". Please let me know if that helps.
